'use strict';function u(f,a,b,d){f.A.kc(f.Za,a,b,d,void 0)}function E(f,a,b,d){f.A.qa?u(f,a,b,d):f.A.df()._OnMessageFromDOM({type:"event",component:f.Za,handler:a,dispatchOpts:d||null,data:b,responseId:null})}function G(f,a,b){f.A.C(f.Za,a,b)}function J(f,a){for(const [b,d]of a)G(f,b,d)}function K(f){f.Pb||(f.A.Pe(f.Zd),f.Pb=!0)}window.Qa=class{constructor(f,a){this.A=f;this.Za=a;this.Pb=!1;this.Zd=()=>this.Da()}cd(){}Da(){}};function L(f){-1!==f.Oa&&(self.clearTimeout(f.Oa),f.Oa=-1)}
window.Ge=class{constructor(f,a){this.Kc=f;this.rg=a;this.Oa=-1;this.Qb=-Infinity;this.$d=()=>{this.Oa=-1;this.Qb=Date.now();this.eb=!0;this.Kc();this.eb=!1};this.Id=this.eb=!1}c(){L(this);this.$d=this.Kc=null}};"use strict";function M(f,a){G(f,"get-element",b=>{const d=f.ca.get(b.elementId);return a(d,b)})}
window.Kg=class extends self.Qa{constructor(f,a){super(f,a);this.ca=new Map;this.Jc=!0;J(this,[["create",()=>{throw Error("required override");}],["destroy",b=>{{b=b.elementId;const d=this.ca.get(b);this.Jc&&d.parentElement.removeChild(d);this.ca.delete(b)}}],["set-visible",b=>{this.Jc&&(this.ca.get(b.elementId).style.display=b.isVisible?"":"none")}],["update-position",b=>{if(this.Jc){var d=this.ca.get(b.elementId);d.style.left=b.left+"px";d.style.top=b.top+"px";d.style.width=b.width+"px";d.style.height=
b.height+"px";b=b.fontSize;null!==b&&(d.style.fontSize=b+"em")}}],["update-state",b=>{this.ca.get(b.elementId);throw Error("required override");}],["focus",b=>this.Dc(b)],["set-css-style",b=>{this.ca.get(b.elementId).style[b.prop]=b.val}],["set-attribute",b=>{this.ca.get(b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{this.ca.get(b.elementId).removeAttribute(b.name)}]]);M(this,b=>b)}Dc(f){var a=this.ca.get(f.elementId);f.focus?a.focus():a.blur()}};"use strict";
{const f=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);let a=0;function b(h){const c=document.createElement("script");c.async=!1;c.type="module";return h.Bg?new Promise(k=>{const l="c3_resolve_"+a;++a;self[l]=k;c.textContent=h.Eg+`\n\nself["${l}"]();`;document.head.appendChild(c)}):new Promise((k,l)=>{c.onload=k;c.onerror=l;c.src=h;document.head.appendChild(c)})}let d=!1,g=!1;function m(){if(!d){try{new Worker("blob://",{get type(){g=!0}})}catch(h){}d=!0}return g}let p=
new Audio;const x={"audio/webm; codecs=opus":!!p.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!p.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!p.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!p.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!p.canPlayType("audio/mp4"),"audio/mpeg":!!p.canPlayType("audio/mpeg")};p=null;async function A(h){h=await B(h);return(new TextDecoder("utf-8")).decode(h)}function B(h){return new Promise((c,
k)=>{const l=new FileReader;l.onload=n=>c(n.target.result);l.onerror=n=>k(n);l.readAsArrayBuffer(h)})}const v=[];let w=0;window.RealFile=window.File;const C=[],F=new Map,y=new Map;let H=0;const D=[];self.runOnStartup=function(h){if("function"!==typeof h)throw Error("runOnStartup called without a function");D.push(h)};const I=new Set(["cordova","playable-ad","instant-games"]);let e=!1;window.ta=class h{constructor(c){this.qa=c.Gg;this.oa=null;this.F="";this.Yb=c.Dg;this.sb={};this.Ha=this.rb=null;
this.Nb=[];this.gb=this.K=this.Ma=null;this.La=-1;this.wg=()=>this.Cf();this.Ka=[];this.u=c.ae;!this.qa||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&m()||(this.qa=!1);I.has(this.u)&&this.qa&&(console.warn("[C3 runtime] Worker mode is enabled and supported, but is currently disabled in WebViews. Reverting to DOM mode."),this.qa=!1);this.Sb=this.ha=null;"html5"!==this.u&&"playable-ad"!==this.u||"file"!==location.protocol.substr(0,4)||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");
this.C("runtime","cordova-fetch-local-file",k=>this.lf(k));this.C("runtime","create-job-worker",()=>this.mf());"cordova"===this.u?document.addEventListener("deviceready",()=>this.vd(c)):this.vd(c)}c(){this.qc();this.oa&&(this.oa=this.oa.onmessage=null);this.rb&&(this.rb.terminate(),this.rb=null);this.Ha&&(this.Ha.c(),this.Ha=null);this.K&&(this.K.parentElement.removeChild(this.K),this.K=null)}ld(){return f&&"cordova"===this.u}jc(){return f&&I.has(this.u)||navigator.standalone}async vd(c){"macos-wkwebview"===
this.u&&this.Hc({type:"ready"});if("playable-ad"===this.u){this.ha=self.c3_base64files;this.Sb={};await this.Ue();for(let l=0,n=c.Pa.length;l<n;++l){var k=c.Pa[l].toLowerCase();this.Sb.hasOwnProperty(k)?c.Pa[l]={Bg:!0,Eg:this.Sb[k]}:this.ha.hasOwnProperty(k)&&(c.Pa[l]=URL.createObjectURL(this.ha[k]))}}c.xg?this.F=c.xg:(k=location.origin,this.F=("null"===k?"file:///":k)+location.pathname,k=this.F.lastIndexOf("/"),-1!==k&&(this.F=this.F.substr(0,k+1)));c.Ig&&(this.sb=c.Ig);k=new MessageChannel;this.oa=
k.port1;this.oa.onmessage=l=>this._OnMessageFromRuntime(l.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(l=>this.yf(l));this.gb=new self.Ce(this);await N(this.gb);"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this.qa?await this.ff(c,k.port2):await this.ef(c,k.port2)}tc(c){c=this.sb.hasOwnProperty(c)?this.sb[c]:c.endsWith("/workermain.js")&&this.sb.hasOwnProperty("workermain.js")?
this.sb["workermain.js"]:"playable-ad"===this.u&&this.ha.hasOwnProperty(c.toLowerCase())?this.ha[c.toLowerCase()]:c;c instanceof Blob&&(c=URL.createObjectURL(c));return c}async cc(c,k,l){if(c.startsWith("blob:"))return new Worker(c,l);if(this.ld()&&"file:"===location.protocol)return c=await this.ub(this.Yb+c),new Worker(URL.createObjectURL(new Blob([c],{type:"application/javascript"})),l);c=new URL(c,k);if(location.origin!==c.origin){c=await fetch(c);if(!c.ok)throw Error("failed to fetch worker script");
c=await c.blob();return new Worker(URL.createObjectURL(c),l)}return new Worker(c,l)}wa(){return Math.max(window.innerWidth,1)}va(){return Math.max(window.innerHeight,1)}ud(c){var k=this.gb;return{baseUrl:this.F,windowInnerWidth:this.wa(),windowInnerHeight:this.va(),devicePixelRatio:window.devicePixelRatio,isFullscreen:h.Ta(),projectData:c.Pg,previewImageBlobs:window.cr_previewImageBlobs||this.ha,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,previewProjectFileSWUrls:window.cr_previewProjectFiles,
swClientId:window.Ng||"",exportType:c.ae,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.Og,jobScheduler:{inputPort:k.Qc,outputPort:k.Xc,maxNumWorkers:k.tg},supportedAudioFormats:x,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.Yb+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.Yb+"opus.wasm.wasm",isiOSCordova:this.ld(),isiOSWebView:this.jc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async ff(c,k){var l=this.tc(c.Hg);this.rb=await this.cc(l,this.F,
{type:"module",name:"Runtime"});this.K=document.createElement("canvas");this.K.style.display="none";l=this.K.transferControlToOffscreen();document.body.appendChild(this.K);window.c3canvas=this.K;this.rb.postMessage(Object.assign(this.ud(c),{type:"init-runtime",isInWorker:!0,messagePort:k,canvas:l,workerDependencyScripts:c.bd||[],engineScripts:c.Pa,projectScripts:c.ce,mainProjectScript:c.be,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[k,l,...O(this.gb)]);this.Nb=C.map(n=>new n(this));this.td();
self.c3_callFunction=(n,r)=>this.Ma.gf(n,r);"preview"===this.u&&(self.goToLastErrorScript=()=>this.kc("runtime","go-to-last-error-script"))}async ef(c,k){this.K=document.createElement("canvas");this.K.style.display="none";document.body.appendChild(this.K);window.c3canvas=this.K;this.Nb=C.map(q=>new q(this));this.td();var l=c.Pa.map(q=>"string"===typeof q?(new URL(q,this.F)).toString():q);Array.isArray(c.bd)&&l.unshift(...c.bd);l=await Promise.all(l.map(q=>this.xc(q)));await Promise.all(l.map(q=>b(q)));
l=self.C3_ProjectScriptsStatus;const n=c.be,r=c.ce;for(let [q,t]of r)if(t||(t=q),q===n)try{t=await this.xc(t),await b(t),"preview"!==this.u||l[q]||this.Dd(q,"main script did not run to completion")}catch(z){this.Dd(q,z)}else if("scriptsInEvents.js"===q||q.endsWith("/scriptsInEvents.js"))t=await this.xc(t),await b(t);"preview"===this.u&&"object"!==typeof self.Jg.Lg?(this.Gb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(c=Object.assign(this.ud(c),{isInWorker:!1,messagePort:k,canvas:this.K,runOnStartupFunctions:D}),this.xd(),this.Ha=self.C3_CreateRuntime(c),await self.C3_InitRuntime(this.Ha,c))}Dd(c,k){this.Gb();console.error(`[Preview] Failed to load project main script (${c}): `,k);alert(`Failed to load project main script (${c}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}xd(){this.Gb()}Gb(){const c=
window.yg;c&&(c.parentElement.removeChild(c),window.yg=null)}async mf(){const c=await P(this.gb);return{outputPort:c,transferables:[c]}}df(){if(this.qa)throw Error("not available in worker mode");return this.Ha}kc(c,k,l,n,r){this.oa.postMessage({type:"event",component:c,handler:k,dispatchOpts:n||null,data:l,responseId:null},r)}md(c,k,l,n,r){const q=H++,t=new Promise((z,S)=>{y.set(q,{resolve:z,reject:S})});this.oa.postMessage({type:"event",component:c,handler:k,dispatchOpts:n||null,data:l,responseId:q},
r);return t}["_OnMessageFromRuntime"](c){const k=c.type;if("event"===k)return this.sf(c);if("result"===k)this.Ff(c);else if("runtime-ready"===k)this.Gf();else if("alert-error"===k)this.Gb(),alert(c.message);else if("creating-runtime"===k)this.xd();else throw Error(`unknown message '${k}'`);}sf(c){const k=c.component,l=c.handler,n=c.data,r=c.responseId;if(c=F.get(k))if(c=c.get(l)){var q=null;try{q=c(n)}catch(t){console.error(`Exception in '${k}' handler '${l}':`,t);null!==r&&this.Fb(r,!1,""+t);return}if(null===
r)return q;q&&q.then?q.then(t=>this.Fb(r,!0,t)).catch(t=>{console.error(`Rejection from '${k}' handler '${l}':`,t);this.Fb(r,!1,""+t)}):this.Fb(r,!0,q)}else console.warn(`[DOM] No handler '${l}' for component '${k}'`);else console.warn(`[DOM] No event handlers for component '${k}'`)}Fb(c,k,l){let n;l&&l.transferables&&(n=l.transferables);this.oa.postMessage({type:"result",responseId:c,isOk:k,result:l},n)}Ff(c){const k=c.responseId,l=c.isOk;c=c.result;const n=y.get(k);l?n.resolve(c):n.reject(c);y.delete(k)}C(c,
k,l){let n=F.get(c);n||(n=new Map,F.set(c,n));if(n.has(k))throw Error(`[DOM] Component '${c}' already has handler '${k}'`);n.set(k,l)}static tb(c){if(C.includes(c))throw Error("DOM handler already added");C.push(c)}td(){for(const c of this.Nb)if("runtime"===c.Za){this.Ma=c;return}throw Error("cannot find runtime DOM handler");}yf(c){this.kc("debugger","message",c)}Gf(){for(const c of this.Nb)c.cd()}static Ta(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||
e)}static Hb(c){e=!!c}Pe(c){this.Ka.push(c);this.Gc()}Sf(c){c=this.Ka.indexOf(c);if(-1===c)throw Error("invalid callback");this.Ka.splice(c,1);this.Ka.length||this.qc()}Gc(){-1===this.La&&this.Ka.length&&(this.La=requestAnimationFrame(this.wg))}qc(){-1!==this.La&&(cancelAnimationFrame(this.La),this.La=-1)}Cf(){this.La=-1;for(const c of this.Ka)c();this.Gc()}ua(c){this.Ma.ua(c)}Ca(c){this.Ma.Ca(c)}Fc(){this.Ma.Fc()}Ab(c){this.Ma.Ab(c)}Be(){return!!x["audio/webm; codecs=opus"]}async pg(c){c=await this.md("runtime",
"opus-decode",{arrayBuffer:c},null,[c]);return new Float32Array(c)}Ae(c){return/^(?:[a-z\-]+:)?\/\//.test(c)||"data:"===c.substr(0,5)||"blob:"===c.substr(0,5)}kd(c){return!this.Ae(c)}async xc(c){return"cordova"===this.u&&(c.startsWith("file:")||"file:"===location.protocol&&this.kd(c))?(c.startsWith(this.F)&&(c=c.substr(this.F.length)),c=await this.ub(c),URL.createObjectURL(new Blob([c],{type:"application/javascript"}))):c}async lf(c){const k=c.filename;switch(c.as){case "text":return await this.te(k);
case "buffer":return await this.ub(k);default:throw Error("unsupported type");}}fd(c){const k=window.cordova.file.applicationDirectory+"www/"+c.toLowerCase();return new Promise((l,n)=>{window.resolveLocalFileSystemURL(k,r=>{r.file(l,n)},n)})}async te(c){c=await this.fd(c);return await A(c)}rc(){if(v.length&&!(8<=w)){w++;var c=v.shift();this.Ve(c.filename,c.Fg,c.Ag)}}ub(c){return new Promise((k,l)=>{v.push({filename:c,Fg:n=>{w--;this.rc();k(n)},Ag:n=>{w--;this.rc();l(n)}});this.rc()})}async Ve(c,k,
l){try{const n=await this.fd(c),r=await B(n);k(r)}catch(n){l(n)}}Hc(c){if("windows-webview2"===this.u)window.chrome.webview.postMessage(JSON.stringify(c));else if("macos-wkwebview"===this.u)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(c));else throw Error("cannot send wrapper message");}async Ue(){const c=[];for(const [k,l]of Object.entries(this.ha))c.push(this.Te(k,l));await Promise.all(c)}async Te(c,k){if("object"===typeof k)this.ha[c]=new Blob([k.str],{type:k.type}),this.Sb[c]=
k.str;else{let l=await this.bf(k);l||(l=this.Xe(k));this.ha[c]=l}}async bf(c){try{return await (await fetch(c)).blob()}catch(k){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",k),null}}Xe(c){c=this.Mf(c);return this.Se(c.data,c.Cg)}Mf(c){var k=c.indexOf(",");if(0>k)throw new URIError("expected comma in data: uri");var l=c.substring(k+1);
k=c.substring(5,k).split(";");c=k[0]||"";const n=k[2];l="base64"===k[1]||"base64"===n?atob(l):decodeURIComponent(l);return{Cg:c,data:l}}Se(c,k){var l=c.length;let n=l>>2,r=new Uint8Array(l),q=new Uint32Array(r.buffer,0,n),t,z;for(z=t=0;t<n;++t)q[t]=c.charCodeAt(z++)|c.charCodeAt(z++)<<8|c.charCodeAt(z++)<<16|c.charCodeAt(z++)<<24;for(l&=3;l--;)r[z]=c.charCodeAt(z),++z;return new Blob([r],{type:k})}}}"use strict";
{const f=self.ta;function a(e){return e.sourceCapabilities&&e.sourceCapabilities.firesTouchEvents||e.originalEvent&&e.originalEvent.sourceCapabilities&&e.originalEvent.sourceCapabilities.firesTouchEvents}const b=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),d={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},g={dispatchUserScriptEvent:!0},m={dispatchRuntimeEvent:!0};function p(e){return new Promise((h,c)=>{const k=document.createElement("link");k.onload=()=>h(k);k.onerror=l=>c(l);k.rel=
"stylesheet";k.href=e;document.head.appendChild(k)})}function x(e){return new Promise((h,c)=>{const k=new Image;k.onload=()=>h(k);k.onerror=l=>c(l);k.src=e})}async function A(e){e=URL.createObjectURL(e);try{return await x(e)}finally{URL.revokeObjectURL(e)}}function B(e){return new Promise((h,c)=>{let k=new FileReader;k.onload=l=>h(l.target.result);k.onerror=l=>c(l);k.readAsText(e)})}async function v(e,h,c){if(!/firefox/i.test(navigator.userAgent))return await A(e);var k=await B(e);k=(new DOMParser).parseFromString(k,
"image/svg+xml");const l=k.documentElement;if(l.hasAttribute("width")&&l.hasAttribute("height")){const n=l.getAttribute("width"),r=l.getAttribute("height");if(!n.includes("%")&&!r.includes("%"))return await A(e)}l.setAttribute("width",h+"px");l.setAttribute("height",c+"px");k=(new XMLSerializer).serializeToString(k);e=new Blob([k],{type:"image/svg+xml"});return await A(e)}function w(e){do{if(e.parentNode&&e.hasAttribute("contenteditable"))return!0;e=e.parentNode}while(e);return!1}const C=new Set(["input",
"textarea","datalist","select"]),F=new Set(["canvas","body","html"]);function y(e){F.has(e.target.tagName.toLowerCase())&&e.preventDefault()}function H(e){(e.metaKey||e.ctrlKey)&&e.preventDefault()}self.C3_GetSvgImageSize=async function(e){e=await A(e);if(0<e.width&&0<e.height)return[e.width,e.height];{e.style.position="absolute";e.style.left="0px";e.style.top="0px";e.style.visibility="hidden";document.body.appendChild(e);const h=e.getBoundingClientRect();document.body.removeChild(e);return[h.width,
h.height]}};self.C3_RasterSvgImageBlob=async function(e,h,c,k,l){e=await v(e,h,c);const n=document.createElement("canvas");n.width=k;n.height=l;n.getContext("2d").drawImage(e,0,0,h,c);return n};let D=!1;document.addEventListener("pause",()=>D=!0);document.addEventListener("resume",()=>D=!1);function I(){try{return window.parent&&window.parent.document.hasFocus()}catch(e){return!1}}f.tb(class extends self.Qa{constructor(e){super(e,"runtime");this.Nd=!0;this.Na=-1;this.Zc="any";this.Ed=this.Fd=!1;this.Tc=
this.ob=this.ya=null;e.C("canvas","update-size",k=>this.Jf(k));e.C("runtime","invoke-download",k=>this.wf(k));e.C("runtime","raster-svg-image",k=>this.Df(k));e.C("runtime","get-svg-image-size",k=>this.uf(k));e.C("runtime","set-target-orientation",k=>this.Hf(k));e.C("runtime","register-sw",()=>this.Ef());e.C("runtime","post-to-debugger",k=>this.zd(k));e.C("runtime","go-to-script",k=>this.zd(k));e.C("runtime","before-start-ticking",()=>this.kf());e.C("runtime","debug-highlight",k=>this.nf(k));e.C("runtime",
"enable-device-orientation",()=>this.Re());e.C("runtime","enable-device-motion",()=>this.Qe());e.C("runtime","add-stylesheet",k=>this.jf(k));e.C("runtime","alert",k=>this.yc(k));e.C("runtime","hide-cordova-splash",()=>this.vf());const h=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",k=>{const l=k.target;h.has(l.tagName.toLowerCase())||w(l)||k.preventDefault()});const c=e.K;window.addEventListener("selectstart",y);window.addEventListener("gesturehold",y);c.addEventListener("selectstart",
y);c.addEventListener("gesturehold",y);window.addEventListener("touchstart",y,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",y,{passive:!1}),c.addEventListener("pointerdown",y)):c.addEventListener("touchstart",y);this.lb=0;window.addEventListener("mousedown",k=>{1===k.button&&k.preventDefault()});window.addEventListener("mousewheel",H,{passive:!1});window.addEventListener("wheel",H,{passive:!1});window.addEventListener("resize",()=>this.Kf());window.addEventListener("fullscreenchange",
()=>this.Va());window.addEventListener("webkitfullscreenchange",()=>this.Va());window.addEventListener("mozfullscreenchange",()=>this.Va());window.addEventListener("fullscreenerror",k=>this.Ac(k));window.addEventListener("webkitfullscreenerror",k=>this.Ac(k));window.addEventListener("mozfullscreenerror",k=>this.Ac(k));e.jc()&&window.addEventListener("focusout",()=>{{const n=document.activeElement;if(n){var k=n.tagName.toLowerCase();var l=new Set("email number password search tel text url".split(" "));
k="textarea"===k?!0:"input"===k?l.has(n.type.toLowerCase()||"text"):w(n)}else k=!1}k||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=k=>this.Lf(k);this.Ia=new Set;this.Tb=new WeakSet;this.na=!1}kf(){"cordova"===this.A.u?(document.addEventListener("pause",()=>this.Ec(!0)),document.addEventListener("resume",()=>this.Ec(!1))):document.addEventListener("visibilitychange",()=>this.Ec(document.hidden));return{isSuspended:!(!document.hidden&&!D)}}cd(){window.addEventListener("focus",()=>
this.Xa("window-focus"));window.addEventListener("blur",()=>{this.Xa("window-blur",{parentHasFocus:I()});this.lb=0});window.addEventListener("focusin",h=>{h=h.target;(C.has(h.tagName.toLowerCase())||w(h))&&this.Xa("keyboard-blur")});window.addEventListener("keydown",h=>this.yd("keydown",h));window.addEventListener("keyup",h=>this.yd("keyup",h));window.addEventListener("dblclick",h=>this.Bc("dblclick",h,d));window.addEventListener("wheel",h=>this.Af(h));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",
h=>{this.uc(h);this.Wa("pointerdown",h)}),this.A.qa&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.ob=new self.Ge(()=>this.$e(),5),this.ob.Id=!0,window.addEventListener("pointerrawupdate",h=>this.Bf(h))):window.addEventListener("pointermove",h=>this.Wa("pointermove",h)),window.addEventListener("pointerup",h=>this.Wa("pointerup",h)),window.addEventListener("pointercancel",h=>this.Wa("pointercancel",h))):(window.addEventListener("mousedown",h=>{this.uc(h);this.Cc("pointerdown",
h)}),window.addEventListener("mousemove",h=>this.Cc("pointermove",h)),window.addEventListener("mouseup",h=>this.Cc("pointerup",h)),window.addEventListener("touchstart",h=>{this.uc(h);this.Eb("pointerdown",h)}),window.addEventListener("touchmove",h=>this.Eb("pointermove",h)),window.addEventListener("touchend",h=>this.Eb("pointerup",h)),window.addEventListener("touchcancel",h=>this.Eb("pointercancel",h)));const e=()=>this.Fc();window.addEventListener("pointerup",e,!0);window.addEventListener("touchend",
e,!0);window.addEventListener("click",e,!0);window.addEventListener("keydown",e,!0);window.addEventListener("gamepadconnected",e,!0)}Xa(e,h){u(this,e,h||null,m)}wa(){return this.A.wa()}va(){return this.A.va()}Kf(){const e=this.wa(),h=this.va();this.Xa("window-resize",{innerWidth:e,innerHeight:h,devicePixelRatio:window.devicePixelRatio,isFullscreen:f.Ta()});this.A.jc()&&(-1!==this.Na&&clearTimeout(this.Na),this.Ad(e,h,0))}Tf(e,h,c){-1!==this.Na&&clearTimeout(this.Na);this.Na=setTimeout(()=>this.Ad(e,
h,c),48)}Ad(e,h,c){const k=this.wa(),l=this.va();this.Na=-1;k!=e||l!=h?this.Xa("window-resize",{innerWidth:k,innerHeight:l,devicePixelRatio:window.devicePixelRatio,isFullscreen:f.Ta()}):10>c&&this.Tf(k,l,c+1)}Hf(e){this.Zc=e.targetOrientation}lg(){const e=this.Zc;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(e).catch(h=>console.warn("[Construct 3] Failed to lock orientation: ",h));else try{let h=!1;screen.lockOrientation?h=screen.lockOrientation(e):screen.webkitLockOrientation?
h=screen.webkitLockOrientation(e):screen.mozLockOrientation?h=screen.mozLockOrientation(e):screen.msLockOrientation&&(h=screen.msLockOrientation(e));h||console.warn("[Construct 3] Failed to lock orientation")}catch(h){console.warn("[Construct 3] Failed to lock orientation: ",h)}}Va(){const e=f.Ta();e&&"any"!==this.Zc&&this.lg();u(this,"fullscreenchange",{isFullscreen:e,innerWidth:this.wa(),innerHeight:this.va()})}Ac(e){console.warn("[Construct 3] Fullscreen request failed: ",e);u(this,"fullscreenerror",
{isFullscreen:f.Ta(),innerWidth:this.wa(),innerHeight:this.va()})}Ec(e){e?this.A.qc():this.A.Gc();u(this,"visibilitychange",{hidden:e})}yd(e,h){"Backspace"===h.key&&y(h);const c=b.get(h.code)||h.code;E(this,e,{code:c,key:h.key,which:h.which,repeat:h.repeat,altKey:h.altKey,ctrlKey:h.ctrlKey,metaKey:h.metaKey,shiftKey:h.shiftKey,timeStamp:h.timeStamp},d)}Af(e){u(this,"wheel",{clientX:e.clientX,clientY:e.clientY,pageX:e.pageX,pageY:e.pageY,deltaX:e.deltaX,deltaY:e.deltaY,deltaZ:e.deltaZ,deltaMode:e.deltaMode,
timeStamp:e.timeStamp},d)}Bc(e,h,c){a(h)||E(this,e,{button:h.button,buttons:h.buttons,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,timeStamp:h.timeStamp},c)}Cc(e,h){if(!a(h)){var c=this.lb;"pointerdown"===e&&0!==c?e="pointermove":"pointerup"===e&&0!==h.buttons&&(e="pointermove");E(this,e,{pointerId:1,pointerType:"mouse",button:h.button,buttons:h.buttons,lastButtons:c,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,width:0,height:0,pressure:0,tangentialPressure:0,
tiltX:0,tiltY:0,twist:0,timeStamp:h.timeStamp},d);this.lb=h.buttons;this.Bc(h.type,h,g)}}Wa(e,h){if(this.ob&&"pointermove"!==e){var c=this.ob;c.eb||(L(c),c.Qb=Date.now())}c=0;"mouse"===h.pointerType&&(c=this.lb);E(this,e,{pointerId:h.pointerId,pointerType:h.pointerType,button:h.button,buttons:h.buttons,lastButtons:c,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,width:h.width||0,height:h.height||0,pressure:h.pressure||0,tangentialPressure:h.tangentialPressure||0,tiltX:h.tiltX||0,
tiltY:h.tiltY||0,twist:h.twist||0,timeStamp:h.timeStamp},d);"mouse"===h.pointerType&&(c="mousemove","pointerdown"===e?c="mousedown":"pointerup"===e&&(c="mouseup"),this.Bc(c,h,g),this.lb=h.buttons)}Bf(e){this.Tc=e;e=this.ob;if(-1===e.Oa){var h=Date.now(),c=h-e.Qb,k=e.rg;c>=k&&e.Id?(e.Qb=h,e.eb=!0,e.Kc(),e.eb=!1):e.Oa=self.setTimeout(e.$d,Math.max(k-c,4))}}$e(){this.Wa("pointermove",this.Tc);this.Tc=null}Eb(e,h){for(let c=0,k=h.changedTouches.length;c<k;++c){const l=h.changedTouches[c];E(this,e,{pointerId:l.identifier,
pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:l.clientX,clientY:l.clientY,pageX:l.pageX,pageY:l.pageY,width:2*(l.radiusX||l.webkitRadiusX||0),height:2*(l.radiusY||l.webkitRadiusY||0),pressure:l.force||l.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:l.rotationAngle||0,timeStamp:h.timeStamp},d)}}uc(e){window!==window.top&&window.focus();this.wd(e.target)&&document.activeElement&&!this.wd(document.activeElement)&&document.activeElement.blur()}wd(e){return!e||e===document||
e===window||e===document.body||"canvas"===e.tagName.toLowerCase()}Re(){this.Fd||(this.Fd=!0,window.addEventListener("deviceorientation",e=>this.qf(e)),window.addEventListener("deviceorientationabsolute",e=>this.rf(e)))}Qe(){this.Ed||(this.Ed=!0,window.addEventListener("devicemotion",e=>this.pf(e)))}qf(e){u(this,"deviceorientation",{absolute:!!e.absolute,alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0,timeStamp:e.timeStamp,webkitCompassHeading:e.webkitCompassHeading,webkitCompassAccuracy:e.webkitCompassAccuracy},
d)}rf(e){u(this,"deviceorientationabsolute",{absolute:!!e.absolute,alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0,timeStamp:e.timeStamp},d)}pf(e){let h=null;var c=e.acceleration;c&&(h={x:c.x||0,y:c.y||0,z:c.z||0});c=null;var k=e.accelerationIncludingGravity;k&&(c={x:k.x||0,y:k.y||0,z:k.z||0});k=null;const l=e.rotationRate;l&&(k={alpha:l.alpha||0,beta:l.beta||0,gamma:l.gamma||0});u(this,"devicemotion",{acceleration:h,accelerationIncludingGravity:c,rotationRate:k,interval:e.interval,timeStamp:e.timeStamp},
d)}Jf(e){const h=this.A.K;h.style.width=e.styleWidth+"px";h.style.height=e.styleHeight+"px";h.style.marginLeft=e.marginLeft+"px";h.style.marginTop=e.marginTop+"px";this.Nd&&(h.style.display="",this.Nd=!1)}wf(e){const h=e.url;e=e.filename;const c=document.createElement("a"),k=document.body;c.textContent=e;c.href=h;c.download=e;k.appendChild(c);c.click();k.removeChild(c)}async Df(e){var h=e.imageBitmapOpts;e=await self.C3_RasterSvgImageBlob(e.blob,e.imageWidth,e.imageHeight,e.surfaceWidth,e.surfaceHeight);
h=h?await createImageBitmap(e,h):await createImageBitmap(e);return{imageBitmap:h,transferables:[h]}}async uf(e){return await self.C3_GetSvgImageSize(e.blob)}async jf(e){await p(e.url)}Fc(){var e=[...this.Ia];this.Ia.clear();if(!this.na)for(const h of e)(e=h.play())&&e.catch(()=>{this.Tb.has(h)||this.Ia.add(h)})}ua(e){if("function"!==typeof e.play)throw Error("missing play function");this.Tb.delete(e);let h;try{h=e.play()}catch(c){this.Ia.add(e);return}h&&h.catch(()=>{this.Tb.has(e)||this.Ia.add(e)})}Ca(e){this.Ia.delete(e);
this.Tb.add(e)}Ab(e){this.na=!!e}vf(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}nf(e){if(e.show){this.ya||(this.ya=document.createElement("div"),this.ya.id="inspectOutline",document.body.appendChild(this.ya));var h=this.ya;h.style.display="";h.style.left=e.left-1+"px";h.style.top=e.top-1+"px";h.style.width=e.width+2+"px";h.style.height=e.height+2+"px";h.textContent=e.name}else this.ya&&(this.ya.style.display="none")}Ef(){window.C3_RegisterSW&&window.C3_RegisterSW()}zd(e){window.c3_postToMessagePort&&
(e.from="runtime",window.c3_postToMessagePort(e))}gf(e,h){return this.A.md(this.Za,"js-invoke-function",{name:e,params:h},void 0,void 0)}yc(e){alert(e.message)}Lf(e){"entered-fullscreen"===e?(f.Hb(!0),this.Va()):"exited-fullscreen"===e?(f.Hb(!1),this.Va()):console.warn("Unknown wrapper message: ",e)}})}"use strict";
async function N(f){if(f.qg)throw Error("already initialised");f.qg=!0;var a=f.Xb.tc("dispatchworker.js");f.Mc=await f.Xb.cc(a,f.F,{name:"DispatchWorker"});a=new MessageChannel;f.Qc=a.port1;f.Mc.postMessage({type:"_init","in-port":a.port2},[a.port2]);f.Xc=await P(f)}function O(f){return[f.Qc,f.Xc]}
async function P(f){const a=f.Od.length;var b=f.Xb.tc("jobworker.js");b=await f.Xb.cc(b,f.F,{name:"JobWorker"+a});const d=new MessageChannel,g=new MessageChannel;f.Mc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);b.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":g.port2},[d.port2,g.port2]);f.Od.push(b);return g.port1}
self.Ce=class{constructor(f){this.Xb=f;this.F=f.F;this.F="preview"===f.u?this.F+"c3/workers/":this.F+f.Yb;this.tg=Math.min(navigator.hardwareConcurrency||2,16);this.Mc=null;this.Od=[];this.Xc=this.Qc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.ta({Gg:!0,Hg:"workermain.js",Pa:["scripts/c3runtime.js"],ce:[],be:"",Dg:"scripts/",bd:[],ae:"html5"}));"use strict";
self.ta.tb(class extends self.Qa{constructor(f){super(f,"mouse");G(this,"cursor",a=>{document.documentElement.style.cursor=a})}});"use strict";function Q(f){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>u(f,"sw-message",a.data))}
function R(f){f=f.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(f).catch(a=>console.warn("[Construct 3] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(f):screen.webkitLockOrientation?a=screen.webkitLockOrientation(f):screen.mozLockOrientation?a=screen.mozLockOrientation(f):screen.msLockOrientation&&(a=screen.msLockOrientation(f));a||console.warn("[Construct 3] Failed to lock orientation")}catch(a){console.warn("[Construct 3] Failed to lock orientation: ",
a)}}
self.ta.tb(class extends self.Qa{constructor(f){super(f,"browser");this.u="";J(this,[["get-initial-state",a=>{this.u=a.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isScirraArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>Q(this)],
["alert",a=>this.yc(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.Dc(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>R(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():
screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var b=a.type;if("back"===b)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===b)window.history.forward();else if("reload"===b)location.reload();else if("url"===b){b=a.url;var d=a.target;a=a.exportType;"windows-uwp"===a&&"undefined"!==typeof Windows?Windows.System.Launcher.launchUriAsync(new Windows.Foundation.Uri(b)):
self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):"preview"===a||"windows-webview2"===a?window.open(b,"_blank"):this.Mg||(2===d?window.top.location=b:1===d?window.parent.location=b:window.location=b)}else"new-window"===b&&(b=a.url,d=a.tag,"windows-uwp"===a.exportType&&"undefined"!==typeof Windows?Windows.System.Launcher.launchUriAsync(new Windows.Foundation.Uri(b)):self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):window.open(b,d))}],
["request-fullscreen",a=>{if("windows-webview2"===this.u||"macos-wkwebview"===this.u)self.ta.Hb(!0),this.A.Hc({type:"set-fullscreen",fullscreen:!0});else{const b={navigationUI:"auto"};a=a.navUI;1===a?b.navigationUI="hide":2===a&&(b.navigationUI="show");a=document.documentElement;a.requestFullscreen?a.requestFullscreen(b):a.mozRequestFullScreen?a.mozRequestFullScreen(b):a.msRequestFullscreen?a.msRequestFullscreen(b):a.webkitRequestFullScreen&&("undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):
a.webkitRequestFullScreen())}}],["exit-fullscreen",()=>{"windows-webview2"===this.u||"macos-wkwebview"===this.u?(self.ta.Hb(!1),this.A.Hc({type:"set-fullscreen",fullscreen:!1})):document.exitFullscreen?document.exitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():document.msExitFullscreen?document.msExitFullscreen():document.webkitCancelFullScreen&&document.webkitCancelFullScreen()}],["set-hash",a=>{location.hash=a.hash}]]);window.addEventListener("online",()=>{u(this,"online-state",
{isOnline:!0})});window.addEventListener("offline",()=>{u(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{u(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",()=>{u(this,"backbutton")});"undefined"!==typeof Windows&&Windows.UI.Core.SystemNavigationManager.getForCurrentView().addEventListener("backrequested",a=>{a.handled=!0;u(this,"backbutton")})}yc(f){alert(f.message)}Dc(f){f=f.isFocus;if("nwjs"===this.u){const a="nwjs"===this.u?
nw.Window.get():null;f?a.focus():a.blur()}else f?window.focus():window.blur()}});"use strict";
{const f=180/Math.PI;self.da=class extends self.Qa{constructor(a){super(a,"audio");this.Mb=this.f=null;this.Ob=this.Pc=!1;this.pa=()=>this.mg();this.aa=[];this.D=[];this.ga=null;this.Pd="";this.Qd=-1;this.nb=new Map;this.Uc=1;this.na=!1;this.$c=0;this.$b=1;this.Nc=0;this.Sd="HRTF";this.Jd="inverse";this.Td=600;this.Rd=1E4;this.Vd=1;this.Ld=this.Yc=!1;this.Yd=this.A.Be();this.ba=new Map;this.Fa=new Set;this.Rc=!1;this.Vc="";this.za=null;self.C3Audio_OnMicrophoneStream=(b,d)=>this.zf(b,d);this.Lb=null;
self.C3Audio_GetOutputStream=()=>this.tf();self.C3Audio_DOMInterface=this;J(this,[["create-audio-context",b=>this.We(b)],["play",b=>this.Nf(b)],["stop",b=>this.jg(b)],["stop-all",()=>this.kg()],["set-paused",b=>this.cg(b)],["set-volume",b=>this.hg(b)],["fade-volume",b=>this.af(b)],["set-master-volume",b=>this.ag(b)],["set-muted",b=>this.bg(b)],["set-silent",b=>this.eg(b)],["set-looping",b=>this.$f(b)],["set-playback-rate",b=>this.dg(b)],["seek",b=>this.Uf(b)],["preload",b=>this.Of(b)],["unload",b=>
this.ng(b)],["unload-all",()=>this.og()],["set-suspended",b=>this.fg(b)],["add-effect",b=>this.rd(b)],["set-effect-param",b=>this.Xf(b)],["remove-effects",b=>this.Qf(b)],["tick",b=>this.If(b)],["load-state",b=>this.xf(b)]])}async We(a){a.isiOSCordova&&(this.Yc=!0);this.$c=a.timeScaleMode;this.Sd=["equalpower","HRTF","soundfield"][a.panningModel];this.Jd=["linear","inverse","exponential"][a.distanceModel];this.Td=a.refDistance;this.Rd=a.maxDistance;this.Vd=a.rolloffFactor;var b={latencyHint:a.latencyHint};
this.Yd||(b.sampleRate=48E3);if("undefined"!==typeof AudioContext)this.f=new AudioContext(b);else if("undefined"!==typeof webkitAudioContext)this.f=new webkitAudioContext(b);else throw Error("Web Audio API not supported");this.sd();this.f.onstatechange=()=>{"running"!==this.f.state&&this.sd()};this.Mb=this.f.createGain();this.Mb.connect(this.f.destination);b=a.listenerPos;this.f.listener.setPosition(b[0],b[1],b[2]);this.f.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>
this.dc();try{await Promise.all(a.preloadList.map(d=>this.Cb(d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct 3] Preloading sounds failed: ",d)}return{sampleRate:this.f.sampleRate}}sd(){this.Ob||(this.Pc=!1,window.addEventListener("pointerup",this.pa,!0),window.addEventListener("touchend",this.pa,!0),window.addEventListener("click",this.pa,!0),window.addEventListener("keydown",this.pa,!0),this.Ob=!0)}Ye(){this.Ob&&(this.Pc=!0,window.removeEventListener("pointerup",this.pa,!0),window.removeEventListener("touchend",
this.pa,!0),window.removeEventListener("click",this.pa,!0),window.removeEventListener("keydown",this.pa,!0),this.Ob=!1)}mg(){if(!this.Pc){var a=this.f;"suspended"===a.state&&a.resume&&a.resume();var b=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=b;d.connect(a.destination);d.start(0);"running"===a.state&&this.Ye()}}W(){return this.f}dc(){return this.f.currentTime}ra(){return this.Mb}hd(a){return(a=this.ba.get(a.toLowerCase()))?a[0].P():this.ra()}de(a,b){a=a.toLowerCase();let d=this.ba.get(a);
d||(d=[],this.ba.set(a,d));b.Zf(d.length);b.gg(a);d.push(b);this.Cd(a)}Cd(a){let b=this.ra();const d=this.ba.get(a);if(d&&d.length){b=d[0].P();for(let g=0,m=d.length;g<m;++g){const p=d[g];g+1===m?p.S(this.ra()):p.S(d[g+1].P())}}for(const g of this.la(a))g.He(b);this.za&&this.Vc===a&&(this.za.disconnect(),this.za.connect(b))}wb(){return this.Uc}xb(){return this.na}Yf(){this.Ld=!0}ve(a,b){return b?this.A.pg(a).then(d=>{const g=this.f.createBuffer(1,d.length,48E3);g.getChannelData(0).set(d);return g}):
new Promise((d,g)=>{this.f.decodeAudioData(a,d,g)})}ua(a){this.A.ua(a)}Ca(a){this.A.Ca(a)}nd(a){let b=0;for(let d=0,g=this.D.length;d<g;++d){const m=this.D[d];this.D[b]=m;m.L===a?m.c():++b}this.D.length=b}Ie(){let a=0;for(let b=0,d=this.aa.length;b<d;++b){const g=this.aa[b];this.aa[a]=g;g.sa()?g.c():++a}this.aa.length=a}*la(a){if(a)for(const b of this.D)self.da.we(b.Z,a)&&(yield b);else this.ga&&!this.ga.T()&&(yield this.ga)}async Cb(a,b,d,g,m){for(const p of this.aa)if(p.Sa()===b)return await T(p),
p;if(m)return null;g&&(this.Yc||this.Ld)&&this.Ie();m="audio/webm; codecs=opus"===d&&!this.Yd;g&&m&&this.Yf();a=!g||this.Yc||m?new self.re(this,a,b,d,g,m):new self.pe(this,a,b,d,g);this.aa.push(a);await T(a);return a}async sc(a,b,d,g,m){for(const p of this.D)if(p.Sa()===b&&(p.bc()||m))return p.Ke(g),p;a=await this.Cb(a,b,d,m);g="html5"===a.Ic?new self.qe(a.i,a,g):new self.se(a.i,a,g);this.D.push(g);return g}Oe(a){let b=this.nb.get(a);if(!b){let d=null;b={ad:0,promise:new Promise(g=>d=g),resolve:d};
this.nb.set(a,b)}b.ad++}Rf(a){const b=this.nb.get(a);if(!b)throw Error("expected pending tag");b.ad--;0===b.ad&&(b.resolve(),this.nb.delete(a))}pc(a){a||(a=this.Pd);return(a=this.nb.get(a))?a.promise:Promise.resolve()}Db(){if(0<this.Fa.size)K(this);else for(const a of this.D)if(a.jd()){K(this);break}}Da(){for(var a of this.Fa)a.Da();a=this.dc();for(var b of this.D)b.Da(a);b=this.D.filter(d=>d.jd()).map(d=>d.Ra());u(this,"state",{tickCount:this.Qd,audioInstances:b,analysers:[...this.Fa].map(d=>d.ye())});
0===b.length&&0===this.Fa.size&&this.Pb&&(this.A.Sf(this.Zd),this.Pb=!1)}lc(a,b,d){u(this,"trigger",{type:a,tag:b,aiid:d})}async Nf(a){const b=a.originalUrl,d=a.url,g=a.type,m=a.isMusic,p=a.tag,x=a.isLooping,A=a.vol,B=a.pos,v=a.panning;let w=a.off;0<w&&!a.trueClock&&(this.f.getOutputTimestamp?(a=this.f.getOutputTimestamp(),w=w-a.performanceTime/1E3+a.contextTime):w=w-performance.now()/1E3+this.f.currentTime);this.Pd=p;this.Oe(p);try{this.ga=await this.sc(b,d,g,p,m),v?(this.ga.zb(!0),this.ga.Je(v.x,
v.y,v.angle,v.innerAngle,v.outerAngle,v.outerGain),v.hasOwnProperty("uid")&&this.ga.Le(v.uid)):this.ga.zb(!1),this.ga.Play(x,A,B,w)}catch(C){console.error("[Construct 3] Audio: error starting playback: ",C);return}finally{this.Rf(p)}K(this)}jg(a){a=a.tag;for(const b of this.la(a))b.ma()}kg(){for(const a of this.D)a.ma()}cg(a){const b=a.tag;a=a.paused;for(const d of this.la(b))a?d.Ua():d.yb();this.Db()}hg(a){const b=a.tag;a=a.vol;for(const d of this.la(b))d.Bb(a)}async af(a){const b=a.tag,d=a.vol,
g=a.duration;a=a.stopOnEnd;await this.pc(b);for(const m of this.la(b))m.xe(d,g,a);this.Db()}ag(a){this.Uc=a.vol;for(const b of this.D)b.Jb()}bg(a){const b=a.tag;a=a.isMuted;for(const d of this.la(b))d.od(a)}eg(a){this.na=a.isSilent;this.A.Ab(this.na);for(const b of this.D)b.Ib()}$f(a){const b=a.tag;a=a.isLooping;for(const d of this.la(b))d.nc(a)}async dg(a){const b=a.tag;a=a.rate;await this.pc(b);for(const d of this.la(b))d.qd(a)}async Uf(a){const b=a.tag;a=a.pos;await this.pc(b);for(const d of this.la(b))d.mc(a)}async Of(a){const b=
a.originalUrl,d=a.url,g=a.type;a=a.isMusic;try{await this.sc(b,d,g,"",a)}catch(m){console.error("[Construct 3] Audio: error preloading: ",m)}}async ng(a){if(a=await this.Cb("",a.url,a.type,a.isMusic,!0))a.c(),a=this.aa.indexOf(a),-1!==a&&this.aa.splice(a,1)}og(){for(const a of this.aa)a.c();this.aa.length=0}fg(a){a=a.isSuspended;!a&&this.f.resume&&this.f.resume();for(const b of this.D)b.oc(a);a&&this.f.suspend&&this.f.suspend()}If(a){this.$b=a.timeScale;this.Nc=a.gameTime;this.Qd=a.tickCount;if(0!==
this.$c)for(var b of this.D)b.Ea();(b=a.listenerPos)&&this.f.listener.setPosition(b[0],b[1],b[2]);for(const d of a.instPans){a=d.uid;for(const g of this.D)g.fa===a&&g.pd(d.x,d.y,d.angle)}}async rd(a){var b=a.type;const d=a.tag;var g=a.params;if("filter"===b)g=new self.je(this,...g);else if("delay"===b)g=new self.he(this,...g);else if("convolution"===b){b=null;try{b=await this.Cb(a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(m){console.log("[Construct 3] Audio: error loading convolution: ",
m);return}g=new self.ge(this,b.$,...g);g.Vf(a.bufferOriginalUrl,a.bufferType)}else if("flanger"===b)g=new self.ke(this,...g);else if("phaser"===b)g=new self.me(this,...g);else if("gain"===b)g=new self.le(this,...g);else if("tremolo"===b)g=new self.oe(this,...g);else if("ringmod"===b)g=new self.ne(this,...g);else if("distortion"===b)g=new self.ie(this,...g);else if("compressor"===b)g=new self.fe(this,...g);else if("analyser"===b)g=new self.ee(this,...g);else throw Error("invalid effect type");this.de(d,
g);this.Bd()}Xf(a){const b=a.index,d=a.param,g=a.value,m=a.ramp,p=a.time;a=this.ba.get(a.tag);!a||0>b||b>=a.length||(a[b].X(d,g,m,p),this.Bd())}Qf(a){a=a.tag.toLowerCase();const b=this.ba.get(a);if(b&&b.length){for(const d of b)d.c();this.ba.delete(a);this.Cd(a)}}Ne(a){this.Fa.add(a);this.Db()}Pf(a){this.Fa.delete(a)}Bd(){this.Rc||(this.Rc=!0,Promise.resolve().then(()=>this.Ze()))}Ze(){const a={};for(const [b,d]of this.ba)a[b]=d.map(g=>g.Ra());u(this,"fxstate",{fxstate:a});this.Rc=!1}async xf(a){const b=
a.saveLoadMode;if(3!==b)for(var d of this.D)d.sa()&&1===b||(d.sa()||2!==b)&&d.ma();for(const g of this.ba.values())for(const m of g)m.c();this.ba.clear();this.$b=a.timeScale;this.Nc=a.gameTime;d=a.listenerPos;this.f.listener.setPosition(d[0],d[1],d[2]);this.na=a.isSilent;this.A.Ab(this.na);this.Uc=a.masterVolume;d=[];for(const g of Object.values(a.effects))d.push(Promise.all(g.map(m=>this.rd(m))));await Promise.all(d);await Promise.all(a.playing.map(g=>this.hf(g,b)));this.Db()}async hf(a,b){if(3!==
b){var d=a.bufferOriginalUrl,g=a.bufferUrl,m=a.bufferType,p=a.isMusic,x=a.tag,A=a.isLooping,B=a.volume,v=a.playbackTime;if(!p||1!==b)if(p||2!==b){b=null;try{b=await this.sc(d,g,m,x,p)}catch(w){console.error("[Construct 3] Audio: error loading audio state: ",w);return}b.Fe(a.pan);b.Play(A,B,v,0);a.isPlaying||b.Ua();b.wc(a)}}}zf(a,b){this.za&&this.za.disconnect();this.Vc=b.toLowerCase();this.za=this.f.createMediaStreamSource(a);this.za.connect(this.hd(this.Vc))}tf(){this.Lb||(this.Lb=this.f.createMediaStreamDestination(),
this.Mb.connect(this.Lb));return this.Lb.stream}static we(a,b){return a.length!==b.length?!1:a===b?!0:a.toLowerCase()===b.toLowerCase()}static Me(a){return a*f}static ue(a){return Math.pow(10,a/20)}static gd(a){return Math.max(Math.min(self.da.ue(a),1),0)}static Ee(a){return Math.log(a)/Math.log(10)*20}static De(a){return self.da.Ee(Math.max(Math.min(a,1),0))}static zg(a,b){return 1-Math.exp(-b*a)}};self.ta.tb(self.da)}"use strict";function T(f){f.Rb||(f.Rb=f.vc());return f.Rb}
self.dd=class{constructor(f,a,b,d,g){this.i=f;this.vg=a;this.Aa=b;this.R=d;this.sg=g;this.Ic="";this.Rb=null}c(){this.Rb=this.i=null}vc(){}W(){return this.i.W()}fc(){return this.vg}Sa(){return this.Aa}ec(){return this.R}sa(){return this.sg}ea(){}};"use strict";
self.pe=class extends self.dd{constructor(f,a,b,d,g){super(f,a,b,d,g);this.Ic="html5";this.J=new Audio;this.J.crossOrigin="anonymous";this.J.autoplay=!1;this.J.preload="auto";this.hb=this.ib=null;this.J.addEventListener("canplaythrough",()=>!0);this.mb=this.W().createGain();this.kb=null;this.J.addEventListener("canplay",()=>{this.ib&&(this.ib(),this.hb=this.ib=null);!this.kb&&this.J&&(this.kb=this.W().createMediaElementSource(this.J),this.kb.connect(this.mb))});this.onended=null;this.J.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.J.addEventListener("error",m=>{console.error(`[Construct 3] Audio '${this.Aa}' error: `,m);this.hb&&(this.hb(m),this.hb=this.ib=null)})}c(){this.i.nd(this);this.mb.disconnect();this.mb=null;this.kb.disconnect();this.kb=null;this.J&&!this.J.paused&&this.J.pause();this.J=this.onended=null;super.c()}vc(){return new Promise((f,a)=>{this.ib=f;this.hb=a;this.J.src=this.Aa})}O(){return this.J}ea(){return this.J.duration}};"use strict";
async function U(f){if(f.xa)return f.xa;var a=f.i.A;if("cordova"===a.u&&a.kd(f.Aa)&&"file:"===location.protocol)f.xa=await a.ub(f.Aa);else{a=await fetch(f.Aa);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);f.xa=await a.arrayBuffer()}}async function V(f){if(f.$)return f.$;f.$=await f.i.ve(f.xa,f.ug);f.xa=null}
self.re=class extends self.dd{constructor(f,a,b,d,g,m){super(f,a,b,d,g);this.Ic="webaudio";this.$=this.xa=null;this.ug=!!m}c(){this.i.nd(this);this.$=this.xa=null;super.c()}async vc(){try{await U(this),await V(this)}catch(f){console.error(`[Construct 3] Failed to load audio '${this.Aa}': `,f)}}ea(){return this.$?this.$.duration:0}};"use strict";
{let f=0;self.ed=class{constructor(a,b,d){this.i=a;this.L=b;this.Z=d;this.Kb=f++;this.M=this.W().createGain();this.M.connect(this.ra());this.B=null;this.fb=!1;this.ja=[0,0,0];this.ia=[0,0,0];this.H=!0;this.V=this.ka=this.G=!1;this.qb=1;this.Ga=!1;this.Y=1;a=this.i.$c;this.Sc=1===a&&!this.sa()||2===a;this.bb=this.fa=-1;this.Xd=!1}c(){this.L=this.i=null;this.B&&(this.B.disconnect(),this.B=null);this.M.disconnect();this.M=null}W(){return this.i.W()}ra(){return this.i.hd(this.Z)}wb(){return this.i.wb()}vb(){return this.Sc?
this.i.Nc:performance.now()/1E3}fc(){return this.L.fc()}Sa(){return this.L.Sa()}ec(){return this.L.ec()}sa(){return this.L.sa()}Ke(a){this.Z=a}T(){}bc(){}IsPlaying(){return!this.H&&!this.G&&!this.T()}jd(){return!this.H&&!this.T()}Ba(){}ea(){return this.L.ea()}Play(){}ma(){}Ua(){}yb(){}Bb(a){this.qb=a;this.M.gain.cancelScheduledValues(0);this.bb=-1;this.M.gain.value=this.hc()}xe(a,b,d){if(!this.Ga){a*=this.wb();var g=this.M.gain;g.cancelScheduledValues(0);var m=this.i.dc();b=m+b;g.setValueAtTime(g.value,
m);g.linearRampToValueAtTime(a,b);this.qb=a;this.bb=b;this.Xd=d}}Jb(){this.Bb(this.qb)}Da(a){-1!==this.bb&&a>=this.bb&&(this.bb=-1,this.Xd&&this.ma(),this.i.lc("fade-ended",this.Z,this.Kb))}hc(){const a=this.qb*this.wb();return isFinite(a)?a:0}od(a){a=!!a;this.Ga!==a&&(this.Ga=a,this.Ib())}xb(){return this.i.xb()}Ib(){}nc(){}qd(a){this.Y!==a&&(this.Y=a,this.Ea())}Ea(){}mc(){}oc(){}zb(a){a=!!a;this.fb!==a&&((this.fb=a)?(this.B||(this.B=this.W().createPanner(),this.B.panningModel=this.i.Sd,this.B.distanceModel=
this.i.Jd,this.B.refDistance=this.i.Td,this.B.maxDistance=this.i.Rd,this.B.rolloffFactor=this.i.Vd),this.M.disconnect(),this.M.connect(this.B),this.B.connect(this.ra())):(this.B.disconnect(),this.M.disconnect(),this.M.connect(this.ra())))}Je(a,b,d,g,m,p){this.fb&&(this.pd(a,b,d),a=self.da.Me,this.B.coneInnerAngle=a(g),this.B.coneOuterAngle=a(m),this.B.coneOuterGain=p)}pd(a,b,d){this.fb&&(this.ja[0]=a,this.ja[1]=b,this.ja[2]=0,this.ia[0]=Math.cos(d),this.ia[1]=Math.sin(d),this.ia[2]=0,this.B.setPosition(...this.ja),
this.B.setOrientation(...this.ia))}Le(a){this.fa=a}ic(){}He(a){const b=this.B||this.M;b.disconnect();b.connect(a)}Ra(){return{aiid:this.Kb,tag:this.Z,duration:this.ea(),volume:this.qb,isPlaying:this.IsPlaying(),playbackTime:this.Ba(),playbackRate:this.Y,uid:this.fa,bufferOriginalUrl:this.fc(),bufferUrl:"",bufferType:this.ec(),isMusic:this.sa(),isLooping:this.V,isMuted:this.Ga,resumePosition:this.ic(),pan:this.ze()}}wc(a){this.qd(a.playbackRate);this.od(a.isMuted)}ze(){if(!this.B)return null;const a=
this.B;return{pos:this.ja,orient:this.ia,cia:a.coneInnerAngle,coa:a.coneOuterAngle,cog:a.coneOuterGain,uid:this.fa}}Fe(a){if(a){this.zb(!0);a=this.B;var b=a.pos;this.ja[0]=b[0];this.ja[1]=b[1];this.ja[2]=b[2];b=a.orient;this.ia[0]=b[0];this.ia[1]=b[1];this.ia[2]=b[2];a.setPosition(...this.ja);a.setOrientation(...this.ia);a.coneInnerAngle=a.cia;a.coneOuterAngle=a.coa;a.coneOuterGain=a.cog;this.fa=a.uid}else this.zb(!1)}}}"use strict";
self.qe=class extends self.ed{constructor(f,a,b){super(f,a,b);this.L.mb.connect(this.M);this.L.onended=()=>this.zc()}c(){this.ma();this.L.mb.disconnect();super.c()}O(){return this.L.O()}zc(){this.H=!0;this.fa=-1;this.i.lc("ended",this.Z,this.Kb)}T(){return this.O().ended}bc(){return this.H?!0:this.T()}Ba(f){let a=this.O().currentTime;f&&(a*=this.Y);this.V||(a=Math.min(a,this.ea()));return a}Play(f,a,b){const d=this.O();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==f&&(d.loop=f);this.Bb(a);d.muted&&
(d.muted=!1);if(d.currentTime!==b)try{d.currentTime=b}catch(g){console.warn(`[Construct 3] Exception seeking audio '${this.L.Sa()}' to position '${b}': `,g)}this.i.ua(d);this.G=this.H=!1;this.V=f;this.Y=1}ma(){const f=this.O();f.paused||f.pause();this.i.Ca(f);this.H=!0;this.G=!1;this.fa=-1}Ua(){if(!(this.G||this.H||this.T())){var f=this.O();f.paused||f.pause();this.i.Ca(f);this.G=!0}}yb(){!this.G||this.H||this.T()||(this.i.ua(this.O()),this.G=!1)}Ib(){this.O().muted=this.Ga||this.xb()}nc(f){f=!!f;
this.V!==f&&(this.V=f,this.O().loop=f)}Ea(){let f=this.Y;this.Sc&&(f*=this.i.$b);try{this.O().playbackRate=f}catch(a){console.warn(`[Construct 3] Unable to set playback rate '${f}':`,a)}}mc(f){if(!this.H&&!this.T())try{this.O().currentTime=f}catch(a){console.warn(`[Construct 3] Error seeking audio to '${f}': `,a)}}ic(){return this.Ba()}oc(f){f?this.IsPlaying()?(this.O().pause(),this.ka=!0):this.ka=!1:this.ka&&(this.i.ua(this.O()),this.ka=!1)}};"use strict";
function W(f){f.j&&f.j.disconnect();f.j=null;f.Ya=null}
self.se=class extends self.ed{constructor(f,a,b){super(f,a,b);this.j=null;this.Ub=d=>this.zc(d);this.Oc=!0;this.Ya=null;this.N=this.Zb=0;this.Wc=1}c(){this.ma();W(this);this.Ub=null;super.c()}zc(f){this.G||this.ka||f.target!==this.Ya||(this.H=this.Oc=!0,this.fa=-1,W(this),this.i.lc("ended",this.Z,this.Kb))}T(){return!this.H&&this.j&&this.j.loop||this.G?!1:this.Oc}bc(){return!this.j||this.H?!0:this.T()}Ba(f){let a;a=this.G?this.N:this.vb()-this.Zb;f&&(a*=this.Y);this.V||(a=Math.min(a,this.ea()));return a}Play(f,
a,b,d){this.Wc=1;this.Bb(a);W(this);this.j=this.W().createBufferSource();this.j.buffer=this.L.$;this.j.connect(this.M);this.Ya=this.j;this.j.onended=this.Ub;this.j.loop=f;this.j.start(d,b);this.G=this.H=this.Oc=!1;this.V=f;this.Y=1;this.Zb=this.vb()-b}ma(){if(this.j)try{this.j.stop(0)}catch(f){}this.H=!0;this.G=!1;this.fa=-1}Ua(){this.G||this.H||this.T()||(this.N=this.Ba(!0),this.V&&(this.N%=this.ea()),this.G=!0,this.j.stop(0))}yb(){!this.G||this.H||this.T()||(W(this),this.j=this.W().createBufferSource(),
this.j.buffer=this.L.$,this.j.connect(this.M),this.Ya=this.j,this.j.onended=this.Ub,this.j.loop=this.V,this.Jb(),this.Ea(),this.Zb=this.vb()-this.N/(this.Y||.001),this.j.start(0,this.N),this.G=!1)}hc(){return super.hc()*this.Wc}Ib(){this.Wc=this.Ga||this.xb()?0:1;this.Jb()}nc(f){f=!!f;this.V!==f&&(this.V=f,this.j&&(this.j.loop=f))}Ea(){let f=this.Y;this.Sc&&(f*=this.i.$b);this.j&&(this.j.playbackRate.value=f)}mc(f){this.H||this.T()||(this.G?this.N=f:(this.Ua(),this.N=f,this.yb()))}ic(){return this.N}oc(f){f?
this.IsPlaying()?(this.ka=!0,this.N=this.Ba(!0),this.V&&(this.N%=this.ea()),this.j.stop(0)):this.ka=!1:this.ka&&(W(this),this.j=this.W().createBufferSource(),this.j.buffer=this.L.$,this.j.connect(this.M),this.Ya=this.j,this.j.onended=this.Ub,this.j.loop=this.V,this.Jb(),this.Ea(),this.Zb=this.vb()-this.N/(this.Y||.001),this.j.start(0,this.N),this.ka=!1)}wc(f){super.wc(f);this.N=f.resumePosition}};"use strict";
{class f{constructor(a){this.i=a;this.f=a.W();this.Md=-1;this.R=this.Z="";this.g=null}c(){this.f=null}Zf(a){this.Md=a}gg(a){this.Z=a}o(){return this.f.createGain()}P(){}S(){}m(a,b,d,g){a.cancelScheduledValues(0);if(0===g)a.value=b;else{var m=this.f.currentTime;g+=m;switch(d){case 0:a.setValueAtTime(b,g);break;case 1:a.setValueAtTime(a.value,m);a.linearRampToValueAtTime(b,g);break;case 2:a.setValueAtTime(a.value,m),a.exponentialRampToValueAtTime(b,g)}}}Ra(){return{type:this.R,tag:this.Z,params:this.g}}}
self.je=class extends f{constructor(a,b,d,g,m,p,x){super(a);this.R="filter";this.g=[b,d,g,m,p,x];this.l=this.o();this.b=this.o();this.b.gain.value=x;this.a=this.o();this.a.gain.value=1-x;this.v=this.f.createBiquadFilter();this.v.type=b;this.v.frequency.value=d;this.v.detune.value=g;this.v.Q.value=m;this.v.gain.vlaue=p;this.l.connect(this.v);this.l.connect(this.a);this.v.connect(this.b)}c(){this.l.disconnect();this.v.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();
this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b,d,g);this.m(this.a.gain,1-b,d,g);break;case 1:this.g[1]=b;this.m(this.v.frequency,b,d,g);break;case 2:this.g[2]=b;this.m(this.v.detune,b,d,g);break;case 3:this.g[3]=b;this.m(this.v.Q,b,d,g);break;case 4:this.g[4]=b,this.m(this.v.gain,b,d,g)}}};self.he=class extends f{constructor(a,b,d,g){super(a);this.R="delay";this.g=[b,d,g];this.l=
this.o();this.b=this.o();this.b.gain.value=g;this.a=this.o();this.a.gain.value=1-g;this.jb=this.o();this.U=this.f.createDelay(b);this.U.delayTime.value=b;this.ab=this.o();this.ab.gain.value=d;this.l.connect(this.jb);this.l.connect(this.a);this.jb.connect(this.b);this.jb.connect(this.U);this.U.connect(this.ab);this.ab.connect(this.jb)}c(){this.l.disconnect();this.b.disconnect();this.a.disconnect();this.jb.disconnect();this.U.disconnect();this.ab.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);
this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){const m=self.da.gd;switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[2]=b;this.m(this.b.gain,b,d,g);this.m(this.a.gain,1-b,d,g);break;case 4:this.g[1]=m(b);this.m(this.ab.gain,m(b),d,g);break;case 5:this.g[0]=b,this.m(this.U.delayTime,b,d,g)}}};self.ge=class extends f{constructor(a,b,d,g){super(a);this.R="convolution";this.g=[d,g];this.Hd=this.Gd="";this.l=this.o();this.b=this.o();this.b.gain.value=g;this.a=this.o();this.a.gain.value=
1-g;this.$a=this.f.createConvolver();this.$a.normalize=d;this.$a.buffer=b;this.l.connect(this.$a);this.l.connect(this.a);this.$a.connect(this.b)}c(){this.l.disconnect();this.$a.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[1]=b,this.m(this.b.gain,b,d,g),this.m(this.a.gain,1-b,d,g)}}Vf(a,b){this.Gd=a;this.Hd=b}Ra(){const a=
super.Ra();a.bufferOriginalUrl=this.Gd;a.bufferUrl="";a.bufferType=this.Hd;return a}};self.ke=class extends f{constructor(a,b,d,g,m,p){super(a);this.R="flanger";this.g=[b,d,g,m,p];this.l=this.o();this.a=this.o();this.a.gain.value=1-p/2;this.b=this.o();this.b.gain.value=p/2;this.cb=this.o();this.cb.gain.value=m;this.U=this.f.createDelay(b+d);this.U.delayTime.value=b;this.s=this.f.createOscillator();this.s.frequency.value=g;this.I=this.o();this.I.gain.value=d;this.l.connect(this.U);this.l.connect(this.a);
this.U.connect(this.b);this.U.connect(this.cb);this.cb.connect(this.U);this.s.connect(this.I);this.I.connect(this.U.delayTime);this.s.start(0)}c(){this.s.stop(0);this.l.disconnect();this.U.disconnect();this.s.disconnect();this.I.disconnect();this.a.disconnect();this.b.disconnect();this.cb.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[4]=b;this.m(this.b.gain,
b/2,d,g);this.m(this.a.gain,1-b/2,d,g);break;case 6:this.g[1]=b/1E3;this.m(this.I.gain,b/1E3,d,g);break;case 7:this.g[2]=b;this.m(this.s.frequency,b,d,g);break;case 8:this.g[3]=b/100,this.m(this.cb.gain,b/100,d,g)}}};self.me=class extends f{constructor(a,b,d,g,m,p,x){super(a);this.R="phaser";this.g=[b,d,g,m,p,x];this.l=this.o();this.a=this.o();this.a.gain.value=1-x/2;this.b=this.o();this.b.gain.value=x/2;this.v=this.f.createBiquadFilter();this.v.type="allpass";this.v.frequency.value=b;this.v.detune.value=
d;this.v.Q.value=g;this.s=this.f.createOscillator();this.s.frequency.value=p;this.I=this.o();this.I.gain.value=m;this.l.connect(this.v);this.l.connect(this.a);this.v.connect(this.b);this.s.connect(this.I);this.I.connect(this.v.frequency);this.s.start(0)}c(){this.s.stop(0);this.l.disconnect();this.v.disconnect();this.s.disconnect();this.I.disconnect();this.a.disconnect();this.b.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,
b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b/2,d,g);this.m(this.a.gain,1-b/2,d,g);break;case 1:this.g[0]=b;this.m(this.v.frequency,b,d,g);break;case 2:this.g[1]=b;this.m(this.v.detune,b,d,g);break;case 3:this.g[2]=b;this.m(this.v.Q,b,d,g);break;case 6:this.g[3]=b;this.m(this.I.gain,b,d,g);break;case 7:this.g[4]=b,this.m(this.s.frequency,b,d,g)}}};self.le=class extends f{constructor(a,b){super(a);this.R="gain";this.g=[b];this.h=this.o();this.h.gain.value=
b}c(){this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,d,g){const m=self.da.gd;switch(a){case 4:this.g[0]=m(b),this.m(this.h.gain,m(b),d,g)}}};self.oe=class extends f{constructor(a,b,d){super(a);this.R="tremolo";this.g=[b,d];this.h=this.o();this.h.gain.value=1-d/2;this.s=this.f.createOscillator();this.s.frequency.value=b;this.I=this.o();this.I.gain.value=d/2;this.s.connect(this.I);this.I.connect(this.h.gain);this.s.start(0)}c(){this.s.stop(0);this.s.disconnect();
this.I.disconnect();this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.h.gain,1-b/2,d,g);this.m(this.I.gain,b/2,d,g);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,d,g)}}};self.ne=class extends f{constructor(a,b,d){super(a);this.R="ringmod";this.g=[b,d];this.l=this.o();this.b=this.o();this.b.gain.value=d;this.a=this.o();this.a.gain.value=1-d;this.pb=this.o();this.pb.gain.value=
0;this.s=this.f.createOscillator();this.s.frequency.value=b;this.s.connect(this.pb.gain);this.s.start(0);this.l.connect(this.pb);this.l.connect(this.a);this.pb.connect(this.b)}c(){this.s.stop(0);this.s.disconnect();this.pb.disconnect();this.l.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.b.gain,b,d,g);
this.m(this.a.gain,1-b,d,g);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,d,g)}}};self.ie=class extends f{constructor(a,b,d,g,m,p){super(a);this.R="distortion";this.g=[b,d,g,m,p];this.l=this.o();this.Wb=this.o();this.Vb=this.o();this.Wf(g,m);this.b=this.o();this.b.gain.value=p;this.a=this.o();this.a.gain.value=1-p;this.ac=this.f.createWaveShaper();this.Lc=new Float32Array(65536);this.cf(b,d);this.ac.curve=this.Lc;this.l.connect(this.Wb);this.l.connect(this.a);this.Wb.connect(this.ac);this.ac.connect(this.Vb);
this.Vb.connect(this.b)}c(){this.l.disconnect();this.Wb.disconnect();this.ac.disconnect();this.Vb.disconnect();this.b.disconnect();this.a.disconnect();super.c()}Wf(a,b){.01>a&&(a=.01);this.Wb.gain.value=a;this.Vb.gain.value=Math.pow(1/a,.6)*b}cf(a,b){for(let d=0;32768>d;++d){let g=d/32768;g=this.ig(g,a,b);this.Lc[32768+d]=g;this.Lc[32768-d-1]=-g}}ig(a,b,d){d=1.05*d*b-b;const g=0>a?-a:a;return(g<b?g:b+d*self.da.zg(g-b,1/d))*(0>a?-1:1)}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();
this.a.connect(a)}P(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[4]=b,this.m(this.b.gain,b,d,g),this.m(this.a.gain,1-b,d,g)}}};self.fe=class extends f{constructor(a,b,d,g,m,p){super(a);this.R="compressor";this.g=[b,d,g,m,p];this.h=this.f.createDynamicsCompressor();this.h.threshold.value=b;this.h.knee.value=d;this.h.ratio.value=g;this.h.attack.value=m;this.h.release.value=p}c(){this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}};
self.ee=class extends f{constructor(a,b,d){super(a);this.R="analyser";this.g=[b,d];this.h=this.f.createAnalyser();this.h.fftSize=b;this.h.smoothingTimeConstant=d;this.Kd=new Float32Array(this.h.frequencyBinCount);this.Wd=new Uint8Array(b);this.Ud=this.Ja=0;this.i.Ne(this)}c(){this.i.Pf(this);this.h.disconnect();super.c()}Da(){this.h.getFloatFrequencyData(this.Kd);this.h.getByteTimeDomainData(this.Wd);const a=this.h.fftSize;let b=this.Ja=0;for(var d=0;d<a;++d){let g=(this.Wd[d]-128)/128;0>g&&(g=-g);
this.Ja<g&&(this.Ja=g);b+=g*g}d=self.da.De;this.Ja=d(this.Ja);this.Ud=d(Math.sqrt(b/a))}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}ye(){return{tag:this.Z,index:this.Md,peak:this.Ja,rms:this.Ud,binCount:this.h.frequencyBinCount,freqBins:this.Kd}}}};
